import type { Metadata } from "next";
import { } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from '../app/providers';

export const metadata: Metadata = {
    title: "Jarro - NextJS",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <ThemeProvider 
                    attribute='class' 
                    defaultTheme="light" 
                    enableSystem disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
