import type { Metadata } from "next";
import { } from "next/font/google";
import "./globals.css";


export const metadata: Metadata = {
    title: "Jarro - NextJS",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                {children}
            </body>
        </html>
    );
}
